# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0005_auto_20160823_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='date_hired',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='defaultusername', max_length=100),
            preserve_default=False,
        ),
    ]
